name: Deploy Azure Function

on:
  push:
    branches: [ "master" ]
  
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: toca
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure'
  GIN_MODE: 'release'  

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.17.0'
    - run: go build -o '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/handler'
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
